builds:
  -
    binary: manager
    main: ./cmd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X "main.goVersion={{.Env.GOVERSION}}"
    goos:
      - linux
    goarch:
        - amd64

dockers:
    - image_templates:
        - 'mmatczuk/scylla-operator:2'
      binaries:
          - manager
      skip_push: auto
      dockerfile: Dockerfile
      extra_files:
        - cmd
        - pkg
        - vendor
